### ISSUE TITLE
Add default fonts

### ISSUE THREAD

**Issue by krapjost** [parkingspace/knot#9]

**Comment by krapjost** [comment]
@jcha0713 폰트 추가했는데 괜찮은지 한 번 봐주실래요? 그리고 가능하면 한글도 모노스페이스로 하고 싶은데 찾기가 힘드네요.

**Comment by jcha0713** [comment]
일단 한글/영어를 동시에 지원한다는 가정하에 UI 폰트/에디터 폰트 나눠서 생각해봅시다. 한글 에디터용 폰트는 생각해놓은 게 있어서 한번 테스트해볼게요.
